version: '3.8'

services:
  salih-i-netology-prometheus:
    image: prom/prometheus:latest
    container_name: salih-i-netology-prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - salih-i-my-netology-hw

volumes:
  prometheus-data:

networks:
  salih-i-my-netology-hw:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
