services:
  salih-i-netology-prometheus:
    image: prom/prometheus:latest
    container_name: salih-i-netology-prometheus
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - salih-i-my-netology-hw

  salih-i-netology-pushgateway:
    image: prom/pushgateway:latest
    container_name: salih-i-netology-pushgateway
    restart: always
    depends_on:
      - salih-i-netology-prometheus
    ports:
      - "9091:9091"
    networks:
      - salih-i-my-netology-hw

  salih-i-netology-grafana:
    image: grafana/grafana:latest
    container_name: salih-i-netology-grafana
    restart: always
    depends_on:
      - salih-i-netology-prometheus
    ports:
      - "80:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/custom.ini:/etc/grafana/grafana.ini
    environment:
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
    networks:
      - salih-i-my-netology-hw

volumes:
  prometheus-data:
  grafana-data:

networks:
  salih-i-my-netology-hw:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16

